apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: certs
          emptyDir: {}
        - name: trustedroots
          emptyDir: {}
        - name: config
          configMap:
            name: nginx
      containers:
      - image: apiserver:5000/spiffe:latest
        name: spiffe-bundle
        imagePullPolicy: Always
        command:
          - /opt/spiffe/spiffectl
          - --k8s-secret=spiffe-creds
          - --k8s-namespace=kube-system
          - --server=spiffe.kube-system.svc.cluster.local:3443
          - bundle
          - export
          - --watch
          - --id=kube-system.svc.cluster.local
          - --dir=/var/lib/spiffe/roots
          - --exec="/bin/echo updated trusted root bundle"
          - --debug
        volumeMounts:
        - mountPath: /var/lib/spiffe/roots
          name: trustedroots
      - image: apiserver:5000/spiffe:latest
        name: spiffe
        imagePullPolicy: Always
        command:
          - /opt/spiffe/spiffectl
          - --k8s-secret=spiffe-creds
          - --k8s-namespace=kube-system
          - --server=spiffe.kube-system.svc.cluster.local:3443
          - ca
          - sign
          - --renew
          - --ca=kube-system.svc.cluster.local
          - --id=urn:spiffe:nginx.svc.cluster.local:nginx
          - --out-key-file=/var/lib/spiffe/certs/nginx.pem
          - --out-cert-file=/var/lib/spiffe/certs/nginx.cert
          - --common-name=*.kube-system.svc.cluster.local
          - --ttl=10h
          - --exec="/bin/echo updated certificate - need to put something like send signal proxy or whatnot"
          - --debug
        volumeMounts:
        - mountPath: /var/lib/spiffe/certs
          name: certs
      - image: nginx:1.9.1
        name: nginx
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/spiffe/certs
          name: certs
        - mountPath: /var/lib/spiffe/roots
          name: trustedroots
        - mountPath: /etc/nginx/conf.d
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: kube-system
  labels:
    app: nginx
spec:
  ports:
  - name: nginx
    port: 443
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: nginx
data:
  default.conf: |
    server {
        listen       443 ssl;
        server_name  nginx.kube-system.svc.cluster.local;
        ssl_certificate         /var/lib/spiffe/certs/nginx.cert;
        ssl_certificate_key     /var/lib/spiffe/certs/nginx.pem;
        ssl_client_certificate  /var/lib/spiffe/roots/certauthority.kube-system.svc.cluster.local.pem;
        ssl_verify_client       on;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        location / {
            return 200 'hello, SPIFFE!';
        }
    }
